// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3b2OvAWC38wPw-yxDtlU9tBB1BDsVbVQ',
    appId: '1:1015089431170:web:aa0b110a8c6f8984b4ea9b',
    messagingSenderId: '1015089431170',
    projectId: 'wanderin-apac',
    authDomain: 'wanderin-apac.firebaseapp.com',
    storageBucket: 'wanderin-apac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR1FjWQlgNq0Yx2bp5eCxg4oFjUZ6yvxo',
    appId: '1:1015089431170:android:6f33227123713eedb4ea9b',
    messagingSenderId: '1015089431170',
    projectId: 'wanderin-apac',
    storageBucket: 'wanderin-apac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3O9zbKk4Bm5Y6lJXqDvqKzNkjyIkCNKA',
    appId: '1:1015089431170:ios:6ec3d2de183e2460b4ea9b',
    messagingSenderId: '1015089431170',
    projectId: 'wanderin-apac',
    storageBucket: 'wanderin-apac.firebasestorage.app',
    iosBundleId: 'com.example.clickCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3O9zbKk4Bm5Y6lJXqDvqKzNkjyIkCNKA',
    appId: '1:1015089431170:ios:e2d7ad4be4c365abb4ea9b',
    messagingSenderId: '1015089431170',
    projectId: 'wanderin-apac',
    storageBucket: 'wanderin-apac.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3b2OvAWC38wPw-yxDtlU9tBB1BDsVbVQ',
    appId: '1:1015089431170:web:ae8678a51c14a821b4ea9b',
    messagingSenderId: '1015089431170',
    projectId: 'wanderin-apac',
    authDomain: 'wanderin-apac.firebaseapp.com',
    storageBucket: 'wanderin-apac.firebasestorage.app',
  );
}
